GEMINI_API_KEY = "AIzaSyB0xnyOcnwOQEb2EMWNRUcPq6PwdhRxSIo"
ALPHA_VANTAGE_KEY = "YHXXV65N36WSEMAF"
FMP_KEY = "Ksd4nUJfWMKAGWgLJQBpgmpprBfWKILp"
[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "wq65CR3vooi04v-oVN_Td0cmAOcme2CjKYqU1iJQkinaawiBg46f8qUGhqQ3fEP5EjEl4uaz7puSNLDX0c6z2g==" # Use the secret you provided

[auth.hanko]
client_id = "85692ddf-2884-420d-a3f4-e37919f5a209" # Use your ID
client_secret = "wq65CR3vooi04v-oVN_Td0cmAOcme2CjKYqU1iJQkinaawiBg46f8qUGhqQ3fEP5EjEl4uaz7puSNLDX0c6z2g=="
server_metadata_url = "https://85692ddf-2884-420d-a3f4-e37919f5a209.hanko.io/.well-known/openid-configuration"
