GEMINI_API_KEY = "AIzaSyB0xnyOcnwOQEb2EMWNRUcPq6PwdhRxSIo"
ALPHA_VANTAGE_KEY = "YHXXV65N36WSEMAF"
FMP_KEY = "Ksd4nUJfWMKAGWgLJQBpgmpprBfWKILp"
[auth]

cookie_secret = "BuhUY-JviMkbDWLrqUUItP5tUOrgciotQhh8wsSGhC0EFzEiFIEnaYSP75h99WMko7674zHAvmEw8YY0zRfk2A=="

[auth.hanko]
client_id = "1c492a9d-cabf-4a93-aaac-5c8b2821f330"
client_secret = "BuhUY-JviMkbDWLrqUUItP5tUOrgciotQhh8wsSGhC0EFzEiFIEnaYSP75h99WMko7674zHAvmEw8YY0zRfk2A==" # Use the API Key from Hanko dashboard, NOT the ID
server_metadata_url = "https://passkeys.hanko.io/1c492a9d-cabf-4a93-aaac-5c8b2821f330"
