GEMINI_API_KEY = "AIzaSyB0xnyOcnwOQEb2EMWNRUcPq6PwdhRxSIo"
ALPHA_VANTAGE_KEY = "YHXXV65N36WSEMAF"
FMP_KEY = "Ksd4nUJfWMKAGWgLJQBpgmpprBfWKILp"
[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "wq65CR3vooi04v-oVN_Td0cmAOcme2CjKYqU1iJQkinaawiBg46f8qUGhqQ3fEP5EjEl4uaz7puSNLDX0c6z2g=="

[auth.hanko]
client_id = "1c492a9d-cabf-4a93-aaac-5c8b2821f330"
client_secret = "wq65CR3vooi04v-oVN_Td0cmAOcme2CjKYqU1iJQkinaawiBg46f8qUGhqQ3fEP5EjEl4uaz7puSNLDX0c6z2g==" # Use the API Key from Hanko dashboard, NOT the ID
server_metadata_url = "https://1c492a9d-cabf-4a93-aaac-5c8b2821f330.hanko.io/.well-known/openid-configuration"
